### ISSUE TITLE
COSupervisors ambiguity

### ISSUE THREAD

**Issue by ghost** [lorenzobn/polito-se2-23-08#1]
The guidelines are:

> Internal co-supervisors are just professors, external co-supervisors are unknown to the systems except for they name and email

And also:

> There can be from no to many co-supervisors in any proposal

Currently, the DB doesn't support this. Currently the cosupervisor can be at most one per thesis_proposal, and there is no difference between internal and external co-supervisor.

**Comment by s316741** [comment]
The DB should be able to add unlimited co-supervisors

**Comment by ghost** [comment]
It should be fixed by the [last commit](https://github.com/lorenzobn/polito-se2-23-08/commit/cffe2093cd9fa0d1e605ee59f2e2ce4c72139c4f#diff-28d5436d07198fd53b668ea658c16326de847d31fa4bd998070fd98a9085a68f).
