### ISSUE TITLE
Open attached PDF on a new tab rather than force download

### ISSUE THREAD

**Issue by demoa00** [lorenzobn/polito-se2-23-08#106]
As a professor, when I want to open the attached pdf file to a student's cv, I will prefer to choose if open the pdf on a new browser tab or directly download it (nowadays always browser support it),  because for example i don't want undred of file downloaded on my pc, if i have to manage a lot of application.

**Comment by ghost** [comment]
Hello!

Thank you for your feedback. As we showed during the demo, this actually depends on your download manager. Most of the times, nowadays this is not an issue because the built-in PDF reader takes care of opening the PDF without downloading it.
