### ISSUE TITLE
Logout function

### ISSUE THREAD

**Issue by RiccardoVukovic320029** [lorenzobn/polito-se2-23-08#11]
Hello everyone, to make things simpler and smoother we will need a function to let a user logout

**Comment by ghost** [comment]
Hello Riccardo,

Yes. There should be something like this in the navbar, as mentioned in #10 .  Can you have a look at it? @RiccardoVukovic320029

**Comment by RiccardoVukovic320029** [comment]
Hello Lorenzo, 
issue in #10  has been fixed. I have added a logout button in the profile dropdown, but it's needed a backend function that allows to perform a logout. I'll take care of connecting the logout button to this functionality after its creation

**Comment by ghost** [comment]
Great Riccardo. We'll do it soon, taking also into consideration the external IDP work.

**Comment by ghost** [comment]
Done in [this commit](https://github.com/teamEightTO/polito-se2-23-08/commit/8c879cc7f0fe27d1f63f365efb5b19df5a25969a).

Closing.
