### ISSUE TITLE
Demo Feedback: Group should be removed from the InsertProposal Functionality

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#14]
Hello team, the group should be removed from the InsertProposal functionality as it's related to the professor's view. 

Questions: 

- Does this mean professor are only specific to each group?
- Do we change the database based on table professor-->professor.id-->group and each professor will only see applications, or add thesis proposals based on the group?

**Comment by ghost** [comment]
Backend part of this is now fixed with the latest commit. Can you @s316741 have a look?

**Comment by s316741** [comment]
@lorenzobn 
this should be here? Just confirming.
![image](https://github.com/lorenzobn/polito-se2-23-08/assets/136931976/783aee5a-d4a7-48c4-9ebd-4f0722dcef81)

**Comment by ghost** [comment]
Yes, it should be there but it is automatically retrieved server-side.
