### ISSUE TITLE
Code Review: API for co-supervisors insert

### ISSUE THREAD

**Issue by SahandGhavami** [lorenzobn/polito-se2-23-08#15]
Dear backend team,
I need APIs for the InsertProposal page to show the list of co-supervisor, cds/programme,... to the client in dropdowns.

**Comment by ghost** [comment]
Hello Sahand,

Will address this very soon.

**Comment by ghost** [comment]
Hello, this updates has been done in the latest commit. The only API needed was for CdS retrieval. [Look here](https://github.com/lorenzobn/polito-se2-23-08/commit/995792d3f8ed5d5f5db8394fdb6c285762af090a)

**Comment by SahandGhavami** [comment]
Thanks @lorenzobn.

**Comment by ghost** [comment]
Closing this now because it is a duplicate (see #20 ).
