### ISSUE TITLE
E2E Integration Testing: Logout Functionality is not working

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#16]
When I click on the logout button, I am unable to logout from the student dashboard and see the portal page again. 

When I click on login it leads to received-applications#

**Comment by ghost** [comment]
Hello,

This is because backend side this functionality is not yet ready. Will work on it.

**Comment by ghost** [comment]
Closing this because [this commit](https://github.com/teamEightTO/polito-se2-23-08/commit/d914eaaecf29fbe576fabc63453aa28071533d01) implemented it.
