### ISSUE TITLE
E2E Testing (TM-1): InsertProposal functionality is giving the right error whenever I enrich all the fields but not enrich them properly. 

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#17]
![image](https://github.com/lorenzobn/polito-se2-23-08/assets/136931976/f13a5711-c5b6-4a6c-84ce-7c9789d92c1a)

For example here it should be specific and tell me exactly where my input message is wrong. A small text that pops up against that field e.g. the description for the error message.

**Comment by SahandGhavami** [comment]
Hello @s316741, 
I have handled this in the new version that I will push shortly.

**Comment by ghost** [comment]
I close this since it's done.
