### ISSUE TITLE
E2E Testing (TM-1): InsertProposal Functionality should only be visible to the Professor and not the Student. 

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#18]
Here marco.rossi@email.com is a student, therefore if I am authenticated as a student then I should not be able to see the InsertProposal as the InsertProposal functionality is only for the professor.

![image](https://github.com/lorenzobn/polito-se2-23-08/assets/136931976/85b79145-8cc7-4b9b-a7df-d778645fbc1d)
As you can see from the database insert function that marco.rossi is a student.
![image](https://github.com/lorenzobn/polito-se2-23-08/assets/136931976/a1c78c0d-6102-4a07-8deb-2659aad78544)

**Comment by ghost** [comment]
Closing this because it is a duplicate (see #19 )
