### ISSUE TITLE
E2E Testing (TM-1): InsertProposal functionality should have an Error Page when the Student tries to access the InsertProposal

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#19]
Hello as discussed, we should have an error page, when the student tries to access the insertProposal page.

**Comment by ghost** [comment]
Hello,

Yes. The student shouldn't be able to do this, nor access this functionality. It should receive an error. Can you @SahandGhavami please clarify?

**Comment by SahandGhavami** [comment]
Hello dear all,
as in the backend token related to the teacher is needed for creating a proposal, the student can't create any proposal.
Anyway, I will implement a toast message for students that they can not create proposal.

**Comment by SahandGhavami** [comment]
Hello, in the new version the students can see the page but they can't create proposal.

**Comment by ghost** [comment]
Fix coming. Closing.
