### ISSUE TITLE
E2E Testing (TM-1): InsertProposal Text Fields Should Have "Type"  , "Co-Supervisor" , and "External Co-Supervisor" Field

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#20]
![image](https://github.com/lorenzobn/polito-se2-23-08/assets/136931976/4b3c86e5-333a-4ac1-a375-97f7bb677af7)
![image](https://github.com/lorenzobn/polito-se2-23-08/assets/136931976/c71d8e5e-7457-4353-9e59-d8c529519b4f)

We should be having all of these fields, however, Sahand hasn't merged the latest branch maybe the changes are reflected, we can close if it's confirmed.

**Comment by ghost** [comment]
Hello, let's wait for @SahandGhavami confirmation then.

**Comment by SahandGhavami** [comment]
Hello dear all,
As the co-supervisor and extended co-supervisor are not at the tasks we decided to implement, I haven't implemented them.
However, I wanted to draw your attention to the type dropdown that was included in the photo sent by @s316741. Additionally, I have added a note section in the next version which I hope will be useful

**Comment by s316741** [comment]
@SahandGhavami as per my understanding, we already have entered some co supervisor and external co-supervisor names in the db, and would like to retrieve the values from the database. 

@lorenzobn please clarify if I am wrong.

**Comment by ghost** [comment]
Hello guys,

Yes. I am preparing two different APIs called getCoSupervisors and getExtCoSupervisors that will allow to retrieve a list of all possible co supervisors so that in the InsertProposal it is possible to search for one. @SahandGhavami Instead of one search widget for both external and internal co supervisors, I recommend creating two separate widgets: one for internal co-supervisors (aka teachers) and one for external co-supervisors.

**Comment by ghost** [comment]
Okay, changes have been applied in the [last commit](https://github.com/teamEightTO/polito-se2-23-08/commit/ed1f3e4c5834aa2d612c9c3676bbb07f4c869c83). 

Two new server-side routes added:
- `/ext-cosupervisors` for getting external co-supervisors name/surname
- `/cosupervisors` for getting internal co-supervisors name/surname (teachers)

@SahandGhavami @s316741 I wait for your feedback on this.

**Comment by SahandGhavami** [comment]
Thanks @lorenzobn. 
In the latest version of the InsertProposal page, I dynamically implemented both types of co-supervisors.

**Comment by SahandGhavami** [comment]
Thanks @lorenzobn.
In the latest version of the InsertProposal page, I dynamically implemented both types of co-supervisors.
