### ISSUE TITLE
E2E Testing: Student should not see the "Insert Proposal" Button, rather should see a "Apply for Thesis Button" or no Button at All

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#22]
Hello, I am seeing this "Insert Proposal" Button for the student, which should not be here, it's a functionality only available for the Professor.

![image](https://github.com/lorenzobn/polito-se2-23-08/assets/136931976/d06a85d7-5e78-49d8-a51e-71cf230b089f)

**Comment by ghost** [comment]
Changes coming. Closing.
