### ISSUE TITLE
E2E Testing (TM-2): In SearchProposal, the Search Word Should NOT be Case sensitive

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#23]
Here I am searching the word "investigating" with small "I" it doesn't work.

![image](https://github.com/lorenzobn/polito-se2-23-08/assets/136931976/66a6a566-64b5-4ebc-80e7-b6e1c58d95bf)

However for "Investigating" with capital first I works find, is it because it's the first word in the sensition? Then the problem is that the search proposal is not case sensitive to the first word in sentence.
![image](https://github.com/lorenzobn/polito-se2-23-08/assets/136931976/4da6dfca-1c78-4403-bd5c-6182baf60c83)

The problem is the same for "maximising"
![image](https://github.com/lorenzobn/polito-se2-23-08/assets/136931976/f75abff8-dbae-43d1-a2ec-61fb4d40aac5)

**Comment by s316741** [comment]
Hello @lorenzobn @RiccardoVukovic320029 even for the Thesis Description it's not case sensitive see the comparison
![image](https://github.com/lorenzobn/polito-se2-23-08/assets/136931976/6023516c-949e-4d41-b3ab-55eea7dca961)
![image](https://github.com/lorenzobn/polito-se2-23-08/assets/136931976/3b338a95-947d-4dc5-a430-aefdc40c2109)

**Comment by ghost** [comment]
It should be fixed with the [last commit](https://github.com/lorenzobn/polito-se2-23-08/commit/381997cafd7deb1797c1b14a3bb0a62029688331). Can you please @s316741 check?

**Comment by ghost** [comment]
Issue solved.
