### ISSUE TITLE
Code review: insert proposal, levels field

### ISSUE THREAD

**Issue by ghost** [lorenzobn/polito-se2-23-08#3]
Hello everyone,

I was looking at [InsertProposal.jsx](https://github.com/lorenzobn/polito-se2-23-08/blob/bef4c18e59deaffb85975fcc10f1ec6e5695d2b2/client/src/components/InsertProposal.jsx), and we have:

`const levels = [
  { value: "Bachelor", label: "Bachelor" },
  { value: "Master", label: "Master" },
  { value: "PhD", label: "PhD" },
];`

Since in the backend we only have Bachelor (BSc in the DB) and Master (MSc in the DB), should the value attribute be "BSc" and "MSc"?

**Comment by SahandGhavami** [comment]
Hello @lorenzobn.
Thanks for your review. I fixed it.

**Comment by ghost** [comment]
Thank you @SahandGhavami. We can close the issue.
