### ISSUE TITLE
TM-1 After the proposal has been inserted, the thesis-list is not updated

### ISSUE THREAD

**Issue by ghost** [lorenzobn/polito-se2-23-08#32]
Hello @SahandGhavami,

I tried the insert Proposal. Everything is fine for the insertion part but, when the toast message shows and the redirection to `/thesis-proposal` is done, the view is not updated with the new proposal inserted. I had to manually refresh the page to see it.

**Comment by serenaaprano13** [comment]
is this fixed? because it works my side. if it is i can close this issue

**Comment by SahandGhavami** [comment]
Hi all,
Also it works on my side.
Maybe we should check it on the meeting.

**Comment by s316741** [comment]
@SahandGhavami @lorenzobn it's also working on my side.

I have checked it.
