### ISSUE TITLE
View Proposal doesn't show the list of keywords and Co-superviors

### ISSUE THREAD

**Issue by ghost** [lorenzobn/polito-se2-23-08#33]
Hello guys,

![image](https://github.com/teamEightTO/polito-se2-23-08/assets/59319678/6b9d49dd-5ebd-4ea1-88df-a5ed08769e8e)
 As the image above shows, when we navigate to a specific proposal, the view currently doesn't render the list of Co-supervisors for that proposal nor the list of active keywords.

The API call to `/thesis-proposals/:thesisId` contains both the internal cosupervisors and external cosupervisors, as well as the keywords.

**Comment by SahandGhavami** [comment]
Hey @lorenzobn, 
the problems have been resolved. Everything should be working smoothly now.
