### ISSUE TITLE
Virtual Clock Needs to Be Implemented in TM-1 InsertProposal and in ProposalPage 

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#36]
Hi guys, we asked the professor and we need to implement the virtual clock

Here are some design suggestions for both backend and frontend: https://docs.google.com/document/d/1Ydq3W5KmHvXRyENkNhmR4xxLL6E6yd__ubhd-PKFu8o/edit

**Comment by s316741** [comment]
We have implemented this, now we are merging the branch and resolving merging conflicts.

**Comment by ghost** [comment]
Done. Closing.
