### ISSUE TITLE
E2E Testing (TM-1): The Keyword is creating an issue despite being filled

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#38]
![image](https://github.com/teamEightTO/polito-se2-23-08/assets/136931976/8410964b-7cab-4402-8920-b6fbd77f5216)
![image](https://github.com/teamEightTO/polito-se2-23-08/assets/136931976/6e8a2a83-faff-4cf9-bf21-e384d0dafd86)

**Comment by ghost** [comment]
I believe you should press enter after each keyword otherwise it isn't rendered. Maybe it can be improved, but try to press enter

**Comment by s316741** [comment]
@lorenzobn 
![image](https://github.com/teamEightTO/polito-se2-23-08/assets/136931976/ecb3f031-91c7-4198-b950-7a6beb3032a6)
Yes it works fine but now I want to delete this thesis proposal as we cannot show this in the presentation

**Comment by s316741** [comment]
@lorenzobn @SahandGhavami one more issue I found out, that it was only adding one keyword, for the other one I tried and it didn't work.

**Comment by s316741** [comment]
![image](https://github.com/teamEightTO/polito-se2-23-08/assets/136931976/bb9e0f17-eefa-4d9f-97a3-a32670851ff3)
This new proposal is also being reflected in the other platforms. 
So we can close this issue when we resolve the multiple keyword issue.

**Comment by s316741** [comment]
@lorenzobn @SahandGhavami closing this issue, and have opened another one for multiple keywords.
