### ISSUE TITLE
E2E Testing (TM-1): The Professor Should NOT add themselves as Co-supervisor

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#39]
![image](https://github.com/teamEightTO/polito-se2-23-08/assets/136931976/46b2883c-eb9b-43c9-951c-b1bd54857ccf)

Hello as you can see that I am signed in as Enrico Bini but I am also seeing myself appearing in the list of co-supervisor which is incorrect.

**Comment by ghost** [comment]
@SahandGhavami We should remove this also from the frontend

**Comment by ghost** [comment]
Fixed in the last commit [here](ttps://github.com/teamEightTO/polito-se2-23-08/commit/fc9bd173181271741563579ba7ecd528a3491a4d)
