### ISSUE TITLE
E2E Testing (TM-1): The Required Knowledge when it's NOT filled should not Give a Toast Message saying that the Required Knowledge is Not Filled

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#40]
![image](https://github.com/teamEightTO/polito-se2-23-08/assets/136931976/703dbd1e-5d87-4dcf-b684-6df1a319bc68)
If you see the image if the required knowledge is empty, we should still be able to submit the proposal.

**Comment by ghost** [comment]
Correct, needs to be addressed. Very easy change I believe. @SahandGhavami

**Comment by serenaaprano13** [comment]
I solved this
