### ISSUE TITLE
E2E Testing (TM-2): The Student should ONLY see the thesis corresponding to their Program

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#41]
Hello in the comparison of requirements vs. the implementation, we discovered the student should ONLY see the proposals relevant to their program.

**Comment by s316741** [comment]
@lorenzobn @RiccardoVukovic320029 as mentioned in DM, we need to update the database entries. 
![image](https://github.com/teamEightTO/polito-se2-23-08/assets/136931976/e7905a9e-aab6-4a0b-bae1-d4df8499c842)
and the Program options available in the InsertProposal should match that.

**Comment by ghost** [comment]
Done. Closing.
