### ISSUE TITLE
E2E Testing (TM-1): Cannot Add Multiple Keywords

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#43]
![image](https://github.com/teamEightTO/polito-se2-23-08/assets/136931976/efc6619b-0226-4f70-88e4-5579c252de7a)
Hello I created this proposal,

And I wasn't able to add multiple keywords.

**Comment by serenaaprano13** [comment]
i can add multiple keywords. you need to press enter once you insert each keyword
![Screenshot 2023-11-28 153325](https://github.com/teamEightTO/polito-se2-23-08/assets/147400853/2db2eddf-1d20-4c6f-80b4-6353bed02ad1)

**Comment by SahandGhavami** [comment]
Hello,
It is working well.
Try again carefully, please.

**Comment by s316741** [comment]
@SahandGhavami I confirm that it's working, thank you
