### ISSUE TITLE
TEST : createProposal - error cases not handled

### ISSUE THREAD

**Issue by Andrew64-bit** [lorenzobn/polito-se2-23-08#53]
2 test cases out of 7 failed :
1) ERROR WITH THE INSERTION OF THE CO SUPERVISORS :
    co-supervisors are added to the Database, but there is no code which handles error cases during the insertion in the DB.
2) ERROR WITH THE INSERTION OF THE KEYWORDS :
    keywords are added to the Database, but there is no code which handles error cases during the insertion in the DB.

**Comment by ghost** [comment]
Hello @Andrew64-bit , is this fixed with the new commits?

**Comment by ghost** [comment]
Issue solved. Closing.
