### ISSUE TITLE
E2E Testing (TM - 8): The Co-supervisor, External Supervisor, and Keywords fields are not there.

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#58]
![image](https://github.com/teamEightTO/polito-se2-23-08/assets/136931976/99757eca-ed68-416c-ac67-e48da141eb33)
Hello these fields are missing, can we aim to complete this?

**Comment by ghost** [comment]
@RiccardoVukovic320029 Completed this. Closing.
