### ISSUE TITLE
E2E Testing (TM - 7): The Confirm Button Doesn't Work when I click on it

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#59]
![image](https://github.com/teamEightTO/polito-se2-23-08/assets/136931976/28aef0ee-bb5d-4ed6-9a84-0acec317f685)

When I want to update the proposal and I click "Confirm" this button doesn't work.

**Comment by ghost** [comment]
Addressed in last commit, as stated in #69. Changing the label, not closing yet. Confirmation of correct behaviour is needed.

**Comment by s316741** [comment]
Thank you this works.
