### ISSUE TITLE
Demo Feedback: The Group in the Insert Proposal is Only for The Professor that Belongs to the Group

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#6]
In this feedback the professor asked us to remove the group from the insert proposal form, as it show in the front page to the professor as to which group it belongs to.

**Comment by ghost** [comment]
Fixed with [last commit](https://github.com/lorenzobn/polito-se2-23-08/commit/18ea4b4658c01f8d89b0c633a0d0412d19806c45).
