### ISSUE TITLE
E2E Testing (TM - 7): Change the Proposal Tab to Active 

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#67]
![image](https://github.com/teamEightTO/polito-se2-23-08/assets/136931976/c31d42a0-83a1-49a8-92ae-6eaa0f770d16)
The Proposal tab should be Active instead of Proposal for better clarity and coherency as we already have a My Proposal Tab

**Comment by serenaaprano13** [comment]
done
