### ISSUE TITLE
E2E Testing (TM - 7): Parameters not passing for UpdateProposal in the backend

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#69]
Hello as Rick might have communicated to you the parameters are not passing.

**Comment by ghost** [comment]
Addressed in the last commit https://github.com/teamEightTO/polito-se2-23-08/commit/ff3914a9faf788ff89479ff9cf485933f204615e

**Comment by ghost** [comment]
Changing the label, not closing yet. Confirmation of correct behaviour is needed.
