### ISSUE TITLE
E2E Testing ( TM -5): If we are in the future, we shouldn't be able to ACCEPT/REJECT 

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#70]
Hello seems like this issue has emerged again.

![image](https://github.com/teamEightTO/polito-se2-23-08/assets/136931976/36aef178-c09c-443b-b535-36c62e52b2f9)

**Comment by ghost** [comment]
Since you @TheGreatDaniad implemented it, can you please check?
