### ISSUE TITLE
Requirement Missing (TM - 5): Once the Professor ACCEPTs the request of ONE User it Should Cancel the Application of Others

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#71]
Hello as per the FAQ we should be cancelling the other applicants with the "cancellation" tag

**Comment by ghost** [comment]
As referenced in the previous message, this issue has been solved with [last commit](https://github.com/teamEightTO/polito-se2-23-08/commit/c9ff6b95a88d746912a7cb64c9d0d27aefcbac62). Closing.
