### ISSUE TITLE
Error Handling Messages

### ISSUE THREAD

**Issue by AngeloCiminos317631** [lorenzobn/polito-se2-23-08#74]
Try to produce more specific Error Message to let the user understand what's wrong in the action is he performing or to show some operation error

**Comment by ghost** [comment]
Hello, thank you again for your feedback. Will address this very soon.

I remember from the demo that this refers to the Update Proposal view. Please feel free to correct me if I am wrong.

**Comment by serenaaprano13** [comment]
Yes, this issue emerges when a professor tries to update a proposal that already has applications. The action cannot be performed (good), but front end there is no error message.

**Comment by SahandGhavami** [comment]
Good morning all,
The mentioned issue has resolved now.

**Comment by SahandGhavami** [comment]
Good morning all,
The mentioned issue has resolved now.
