### ISSUE TITLE
TM-5 (Accept Application): Once the Professor Accepts the Application all the Other Applications Should be Rejected

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#75]
According to FAQ:

- Once the professor accepts one applications, the other pending application should be cancelled, status should change from pending --> cancelled
- Once the professor accepts the proposal, it should move to the ARCHIVE tab
- There is only one decision and that is final
- For TM-6 we should have a "cancellation" tab

**Comment by ghost** [comment]
This issue should have been addressed with [this commit](4ace06369bbb16c3fa954c6468c7ca06bc4b49c8). It was correctly working on my side. Can you please @RiccardoVukovic320029 @s316741 check again?

**Comment by s316741** [comment]
@lorenzobn yes this works thanks, I am closing.
