### ISSUE TITLE
Proposal is not archived after deadline is passed 

### ISSUE THREAD

**Issue by serenaaprano13** [lorenzobn/polito-se2-23-08#79]
I'm in a professor view > My Proposals. 
If we move the virtual clock forward, a proposal that is passed the deadline should go to archive section, but it does not.
Moreover, it should not be shown in the proposal list.
![Screenshot 2024-01-03 181849](https://github.com/teamEightTO/polito-se2-23-08/assets/147400853/ed9dd41b-ea83-4107-be08-59c3ea3428cc)

**Comment by TheGreatDaniad** [comment]
resolved. 
https://github.com/teamEightTO/polito-se2-23-08/commit/cc63cfba8be95ff0839e8de64322dd4f3770018c
