### ISSUE TITLE
Virtual clock is not persisent

### ISSUE THREAD

**Issue by serenaaprano13** [lorenzobn/polito-se2-23-08#80]
According to FAQ, 
Once the tester changes the time, the new time is the same for all the system, even when logging out and then again in another account

In our project, when we log out and in again, the clock is re-set to current time

**Comment by TheGreatDaniad** [comment]
fixed 
https://github.com/teamEightTO/polito-se2-23-08/commit/a28c1ce298bca4166b1c6522d83231c05cc2a7db
