### ISSUE TITLE
You cannot delete a proposal that has already an accepted application

### ISSUE THREAD

**Issue by serenaaprano13** [lorenzobn/polito-se2-23-08#84]
As FAQ says 
When a proposal is deleted but an application to that proposal was already accepted, do we have change the application status or forbid the deletion? You cannot delete a proposal that is archived (e.g. after an application is accepted) 

In our project, we cannot delete a proposal that already has an accepted application (good!), but the delete button still appears and when we try to click on it, a pop up just says "Error occured" without specifing which error. 
We should:
- remove the delete option
OR
- make the pop up more explicit on what is the error

**Comment by ghost** [comment]
Hello, I believe that both strategies must be used. Deleting the button from the front-end and check if the API returns the appropriate message. That messsage, if returned properly, should be visualized in the UI.

**Comment by s316741** [comment]
@lorenzobn I can confirm that this works, when I delete an application where there is no application decision has been taken, it cancels the pending application. We can close this. 

Thank you.
