### ISSUE TITLE
Deletion of a proposal does not work

### ISSUE THREAD

**Issue by serenaaprano13** [lorenzobn/polito-se2-23-08#86]
As a professor, if i want to delete a proposal (which does not have accepted application yet), i get a pop up informing there is an unexpected error.

**Comment by ghost** [comment]
Hello Serena, is it a duplicate of #64 ?

**Comment by ghost** [comment]
Should work, at least backend side with the [last commit](https://github.com/teamEightTO/polito-se2-23-08/commit/98b49ac7167b802dec04b2ccb1a1d57f33af758e)
