### ISSUE TITLE
TM - 5 (Accept Application) - Once an application is accepted, it should move to Archive

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#88]
Can we move the proposal that has an accepted application to the archive? 
We should remove it from the MY PROPOSALS and also from APPLICAITONS view

**Comment by ghost** [comment]
Done with [last commit](https://github.com/teamEightTO/polito-se2-23-08/commit/cdff21a8149293d7e6084f132812d2249806059e). Please check.
