### ISSUE TITLE
TM - 10 (Delete Proposal) - When I delete the Proposal as a Professor when I go to the Applications Tab I am still seeing the Proposal

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#93]
Hi Team, 

Can we ensure to remove the proposal from the "application" tab for the professor view once the proposal is deleted?

![image](https://github.com/teamEightTO/polito-se2-23-08/assets/136931976/73d81d19-5183-4fe5-b19c-1b94ac42528a)

**Comment by ghost** [comment]
I believe it is a front-end issue, so please @RiccardoVukovic320029 can you help here?
