### ISSUE TITLE
TM - (Copy Proposal/Delete Proposal) - Once I Copy a Proposal and I Delete it, It still Exists in the Student's View

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#94]
![image](https://github.com/teamEightTO/polito-se2-23-08/assets/136931976/a85f92ae-650e-4093-941d-eee0e8dfe7f8)

**Comment by s316741** [comment]
Steps to Reproduce the Error @lorenzobn 
- Login to Sereno's account, copy the first proposal
- Now delete the copied proposal
- Login to the student's account
- Now you will see the original proposal and the copied proposal both still exist in the THESES view for the student but not for the professor.

**Comment by serenaaprano13** [comment]
this problem occurs everytime we delete a proposal, whether that is a copy from another one or not

**Comment by TheGreatDaniad** [comment]
resolved.
