### ISSUE TITLE
TM-12 Archive Proposal - The Archived Proposal and All the Applications still Exist in the "Application" View for Professor

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#95]
![image](https://github.com/teamEightTO/polito-se2-23-08/assets/136931976/acd5c8d5-ab28-4071-bb6d-f17d569c6a53)
I have manually archived a proposal and the professor is still able to see the proposal and all the associated applications in the application tab.

**Comment by s316741** [comment]
Steps to Reproduce the Error @lorenzobn:

- Login to Bini Enrico
- Archive a Proposal "Machine Learning etc" --> proposal exists in the archive
- Go to Applications the proposal still exists
- Goal remove the archive proposal from:
- APPLICATION --> professor view
- THESES --> student view
- Main landing page for both professor/student view

**Comment by ghost** [comment]
As far as the APPLICATION view for the professor is concerned, can you specify why it should be removed from the section? The problem is in the UI because, even if I can access the list of students who applied to a specific proposal, I should not see the buttons ACCEPT/REJECT. The backend is handling this:

![image](https://github.com/teamEightTO/polito-se2-23-08/assets/59319678/231d65c2-9c45-4ccf-b26c-89d186288469)

**Comment by s316741** [comment]
Okay so we should still see the application list but just without the buttons? and only the states Accepted/Rejected/Cancelled is that correct? @lorenzobn

**Comment by ghost** [comment]
> Okay so we should still see the application list but just without the buttons? and only the states Accepted/Rejected/Cancelled is that correct? @lorenzobn

Yes. For the student view I am working on it.

**Comment by s316741** [comment]
Thanks, @lorenzobn I think removing the buttons once the application is accepted/rejected will resolve this issue.

**Comment by ghost** [comment]
Backend side is fixed for student now.

**Comment by s316741** [comment]
@lorenzobn the archived proposal exists in Student View as well. 
If you archive the proposal this still exists in the student view

**Comment by s316741** [comment]
@lorenzobn opened another issue as I reported. https://github.com/teamEightTO/polito-se2-23-08/issues/101

**Comment by ghost** [comment]
Archived, on my side, shows cancelled proposal. So I assume it is fixed. We need to fix the frontend with the buttons to fix and close the issue.

**Comment by s316741** [comment]
@RiccardoVukovic320029 need help here
