### ISSUE TITLE
TM - 12 (Archive Proposal) - I have to refresh the page to archive a proposal

### ISSUE THREAD

**Issue by s316741** [lorenzobn/polito-se2-23-08#99]
I have to manually refresh the page to archive a proposal.

Steps to Reproduce the Error:

- Archive a proposal from professor's view
- proposal still exists
- Manuall refresh the page
- proposal disappears

**Comment by ghost** [comment]
This issue is frontend. @TheGreatDaniad @SahandGhavami Please have a look

**Comment by SahandGhavami** [comment]
it is fixed now.
